# Generated by Django 5.1.6 on 2026-02-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0005_documento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='error_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documento',
            name='status',
            field=models.CharField(
                choices=[('queued', 'Na fila'), ('processing', 'Processando'), ('done', 'Concluido'), ('error', 'Erro')],
                db_index=True,
                default='queued',
                max_length=20,
            ),
        ),
    ]
